import { z } from 'zod';
import { LOCATION_TYPES, WEATHER_OPTIONS, PRICE_BANDS, REGION_TIERS, SEO_TIERS } from './enums';

export const LocationRowSchema = z.object({
  id: z.number(),
  created_at: z.string(),
  name: z.string().min(1),
  region: z.string(),
  type: z.enum(LOCATION_TYPES),
  description: z.string(),
  website: z.string().nullable(),
  coffee: z.boolean(),
  diaper: z.boolean(),
  alcohol: z.boolean(),
  weather: z.enum(WEATHER_OPTIONS).nullable(),
  place_id: z.string().nullable(),
  last_verified_at: z.string().nullable(),
  distance_from_city_center_km: z.number().nullable(),
  lat: z.number().min(-90).max(90),
  lng: z.number().min(-180).max(180),
  last_verified: z.string().nullable(),
  verification_source: z.string().nullable(),
  min_age: z.number(),
  max_age: z.number(),
  toddler_highlight: z.string().nullable(),
  claimed_by_user_id: z.string().nullable(),
  owner_verified: z.boolean(),
  is_featured: z.boolean(),
  featured_until: z.string().nullable(),
  featured_tier: z.string().nullable(),
  last_owner_update: z.string().nullable(),
  owner_photo_url: z.string().nullable(),
  ai_suitability_score_10: z.number().nullable(),
  ai_suitability_confidence: z.coerce.string().nullable(),
  ai_reviewed_at: z.string().nullable(),
  ai_review_model: z.string().nullable(),
  ai_review_version: z.string().nullable(),
  ai_review_status: z.string().nullable(),
  opening_hours: z.string().nullable(),
  seo_tier: z.enum(SEO_TIERS),
  seo_quality_score: z.number().nullable(),
  seo_title_override: z.string().nullable(),
  seo_description_override: z.string().nullable(),
  seo_intro_override: z.string().nullable(),
  seo_primary_locality: z.string().nullable(),
  seo_canonical_target: z.string().nullable(),
  seo_exclude_from_sitemap: z.boolean(),
  seo_last_decided_at: z.string().nullable(),
  seo_notes: z.string().nullable(),
  price_band: z.enum(PRICE_BANDS).nullable(),
  time_of_day_fit: z.string().nullable(),
  rain_backup_quality: z.string().nullable(),
  shade_or_shelter: z.string().nullable(),
  parking_ease: z.string().nullable(),
  buggy_friendliness: z.string().nullable(),
  toilet_confidence: z.string().nullable(),
  noise_level: z.string().nullable(),
  food_fit: z.string().nullable(),
  play_corner_quality: z.string().nullable(),
  crowd_pattern: z.string().nullable(),
  verification_confidence: z.coerce.string().nullable(),
  verification_mode: z.string().nullable(),
  last_context_refresh_at: z.string().nullable(),
  homepage_featured: z.boolean(),
  photo_url: z.string().nullable(),
  photo_source: z.string().nullable(),
  photo_fetched_at: z.string().nullable(),
  photo_quality: z.number().nullable(),
  slug: z.string().min(1),
});

export const LocationSummarySchema = LocationRowSchema.pick({
  id: true,
  name: true,
  slug: true,
  type: true,
  lat: true,
  lng: true,
  region: true,
  toddler_highlight: true,
  weather: true,
  ai_suitability_score_10: true,
  photo_url: true,
  is_featured: true,
  price_band: true,
});

export const RegionRowSchema = z.object({
  id: z.number(),
  name: z.string(),
  slug: z.string(),
  blurb: z.string().nullable(),
  display_order: z.number(),
  population: z.number().nullable(),
  tier: z.enum(REGION_TIERS),
  schema_type: z.string(),
  is_active: z.boolean(),
  created_at: z.string(),
  updated_at: z.string(),
});

export type LocationRow = z.infer<typeof LocationRowSchema>;
export type LocationSummaryRow = z.infer<typeof LocationSummarySchema>;
export type RegionRow = z.infer<typeof RegionRowSchema>;
