create table if not exists public.locations (
    id bigint generated by default as identity primary key,
    created_at timestamptz default now(),
    name text not null,
    region text,
    type text, -- play, nature, pancake, museum, horeca
    description text,
    website text,
    lat float8,
    lng float8,
    coffee boolean default false,
    diaper boolean default false,
    alcohol boolean default false,
    weather text -- outdoor, indoor, hybrid
);

-- Row Level Security
alter table public.locations enable row level security;

-- Drop existing policy if it exists to avoid errors on retry
drop policy if exists "Allow public read access" on public.locations;

create policy "Allow public read access" 
on public.locations for select 
using (true);
