-- ================================================================
-- PeuterPlannen: Location alcohol audit logging + atomic apply RPC
-- Migration: 20260311_location_alcohol_audit.sql
-- ================================================================

CREATE TABLE IF NOT EXISTS public.location_alcohol_audit_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  scope TEXT NOT NULL CHECK (btrim(scope) <> ''),
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'completed', 'partial', 'failed')),
  agent_count INTEGER NOT NULL DEFAULT 0 CHECK (agent_count >= 0),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at TIMESTAMPTZ,
  summary_json JSONB NOT NULL DEFAULT '{}'::jsonb
);

CREATE INDEX IF NOT EXISTS idx_location_alcohol_audit_runs_status_started
  ON public.location_alcohol_audit_runs (status, started_at DESC);

CREATE TABLE IF NOT EXISTS public.location_alcohol_audit_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id UUID NOT NULL REFERENCES public.location_alcohol_audit_runs(id) ON DELETE CASCADE,
  location_id BIGINT NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  old_alcohol BOOLEAN,
  new_alcohol BOOLEAN,
  decision TEXT NOT NULL CHECK (decision IN ('true', 'false', 'needs_review')),
  confidence NUMERIC(4,3) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
  evidence_source_type TEXT,
  evidence_url TEXT,
  evidence_snippet TEXT,
  reason_short TEXT NOT NULL CHECK (btrim(reason_short) <> ''),
  reason_long TEXT,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  applied_by TEXT NOT NULL DEFAULT 'codex',
  CONSTRAINT location_alcohol_audit_results_run_location_key UNIQUE (run_id, location_id)
);

CREATE INDEX IF NOT EXISTS idx_location_alcohol_audit_results_run_id
  ON public.location_alcohol_audit_results (run_id, location_id);

CREATE INDEX IF NOT EXISTS idx_location_alcohol_audit_results_location_id
  ON public.location_alcohol_audit_results (location_id, applied_at DESC);

CREATE INDEX IF NOT EXISTS idx_location_alcohol_audit_results_decision
  ON public.location_alcohol_audit_results (decision, confidence DESC);

CREATE OR REPLACE FUNCTION public.apply_location_alcohol_audit_result(
  p_run_id UUID,
  p_location_id BIGINT,
  p_decision TEXT,
  p_confidence NUMERIC,
  p_evidence_source_type TEXT,
  p_evidence_url TEXT,
  p_evidence_snippet TEXT,
  p_reason_short TEXT,
  p_reason_long TEXT,
  p_applied_by TEXT DEFAULT 'codex'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_old_alcohol BOOLEAN;
  v_new_alcohol BOOLEAN;
  v_updated BOOLEAN := false;
BEGIN
  IF p_decision NOT IN ('true', 'false', 'needs_review') THEN
    RAISE EXCEPTION 'Unsupported alcohol audit decision: %', p_decision;
  END IF;

  SELECT alcohol
    INTO v_old_alcohol
  FROM public.locations
  WHERE id = p_location_id
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Location % not found', p_location_id;
  END IF;

  IF p_decision = 'true' THEN
    v_new_alcohol := true;
  ELSIF p_decision = 'false' THEN
    v_new_alcohol := false;
  ELSE
    v_new_alcohol := NULL;
  END IF;

  INSERT INTO public.location_alcohol_audit_results (
    run_id,
    location_id,
    old_alcohol,
    new_alcohol,
    decision,
    confidence,
    evidence_source_type,
    evidence_url,
    evidence_snippet,
    reason_short,
    reason_long,
    applied_by
  ) VALUES (
    p_run_id,
    p_location_id,
    v_old_alcohol,
    v_new_alcohol,
    p_decision,
    p_confidence,
    NULLIF(btrim(COALESCE(p_evidence_source_type, '')), ''),
    NULLIF(btrim(COALESCE(p_evidence_url, '')), ''),
    NULLIF(btrim(COALESCE(p_evidence_snippet, '')), ''),
    p_reason_short,
    p_reason_long,
    COALESCE(NULLIF(btrim(COALESCE(p_applied_by, '')), ''), 'codex')
  )
  ON CONFLICT (run_id, location_id)
  DO UPDATE SET
    old_alcohol = EXCLUDED.old_alcohol,
    new_alcohol = EXCLUDED.new_alcohol,
    decision = EXCLUDED.decision,
    confidence = EXCLUDED.confidence,
    evidence_source_type = EXCLUDED.evidence_source_type,
    evidence_url = EXCLUDED.evidence_url,
    evidence_snippet = EXCLUDED.evidence_snippet,
    reason_short = EXCLUDED.reason_short,
    reason_long = EXCLUDED.reason_long,
    applied_at = now(),
    applied_by = EXCLUDED.applied_by;

  IF v_new_alcohol IS NOT NULL AND v_new_alcohol IS DISTINCT FROM v_old_alcohol THEN
    UPDATE public.locations
    SET alcohol = v_new_alcohol
    WHERE id = p_location_id;
    v_updated := true;
  END IF;

  RETURN jsonb_build_object(
    'location_id', p_location_id,
    'old_alcohol', v_old_alcohol,
    'new_alcohol', COALESCE(v_new_alcohol, v_old_alcohol),
    'decision', p_decision,
    'updated', v_updated
  );
END;
$$;

REVOKE ALL ON FUNCTION public.apply_location_alcohol_audit_result(UUID, BIGINT, TEXT, NUMERIC, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.apply_location_alcohol_audit_result(UUID, BIGINT, TEXT, NUMERIC, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT) TO service_role;
