-- ================================================================
-- PeuterPlannen: Location SEO governance + alias support
-- Migration: 20260310b_location_seo_governance.sql
-- ================================================================

-- ----------------------------------------------------------------
-- 1) Extend locations with SEO governance fields
-- ----------------------------------------------------------------
ALTER TABLE public.locations
  ADD COLUMN IF NOT EXISTS seo_tier TEXT NOT NULL DEFAULT 'auto'
    CHECK (seo_tier IN ('auto', 'index', 'support', 'alias')),
  ADD COLUMN IF NOT EXISTS seo_quality_score NUMERIC(5,2)
    CHECK (
      seo_quality_score IS NULL
      OR (seo_quality_score >= 0 AND seo_quality_score <= 100)
    ),
  ADD COLUMN IF NOT EXISTS seo_title_override TEXT,
  ADD COLUMN IF NOT EXISTS seo_description_override TEXT,
  ADD COLUMN IF NOT EXISTS seo_intro_override TEXT,
  ADD COLUMN IF NOT EXISTS seo_primary_locality TEXT,
  ADD COLUMN IF NOT EXISTS seo_canonical_target BIGINT REFERENCES public.locations(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS seo_exclude_from_sitemap BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS seo_last_decided_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS seo_notes TEXT;

-- Keep SEO indexes partial and narrow so they help admin/sitemap lookups
-- without adding much overhead to writes.
CREATE INDEX IF NOT EXISTS idx_locations_seo_tier_nonstandard
  ON public.locations (seo_tier)
  WHERE seo_tier <> 'auto';

CREATE INDEX IF NOT EXISTS idx_locations_seo_quality_score
  ON public.locations (seo_quality_score DESC)
  WHERE seo_quality_score IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_locations_seo_primary_locality
  ON public.locations (seo_primary_locality)
  WHERE seo_primary_locality IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_locations_seo_canonical_target
  ON public.locations (seo_canonical_target)
  WHERE seo_canonical_target IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_locations_seo_excluded_from_sitemap
  ON public.locations (id)
  WHERE seo_exclude_from_sitemap = true;

-- ----------------------------------------------------------------
-- 2) Alias table for alternate/legacy location names
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.location_aliases (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  location_id BIGINT NOT NULL REFERENCES public.locations(id) ON DELETE CASCADE,
  alias TEXT NOT NULL CHECK (btrim(alias) <> ''),
  alias_normalized TEXT CHECK (
    alias_normalized IS NULL
    OR (
      btrim(alias_normalized) <> ''
      AND alias_normalized = lower(alias_normalized)
    )
  ),
  old_region_slug TEXT,
  old_loc_slug TEXT,
  target_url TEXT,
  reason TEXT,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT location_aliases_location_alias_key UNIQUE (location_id, alias)
);

CREATE INDEX IF NOT EXISTS idx_location_aliases_active_location
  ON public.location_aliases (location_id)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_location_aliases_active_alias
  ON public.location_aliases (alias)
  WHERE is_active = true;

CREATE INDEX IF NOT EXISTS idx_location_aliases_active_alias_normalized
  ON public.location_aliases (alias_normalized)
  WHERE alias_normalized IS NOT NULL AND is_active = true;
