-- ================================================================
-- PeuterPlannen: OSM intake + AI scoring pipeline
-- Migration: 20260305_osm_ai_pipeline.sql
-- ================================================================

-- ----------------------------------------------------------------
-- 1) Ingestion runs
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.ingestion_runs (
  id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  run_type           TEXT NOT NULL CHECK (run_type IN ('ingest', 'reaudit')),
  region_root        TEXT NOT NULL,
  with_surroundings  BOOLEAN NOT NULL DEFAULT false,
  status             TEXT NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'done', 'failed')),
  started_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
  finished_at        TIMESTAMPTZ,
  stats_json         JSONB NOT NULL DEFAULT '{}'::jsonb,
  error_text         TEXT
);

CREATE INDEX IF NOT EXISTS idx_ingestion_runs_region_status
  ON public.ingestion_runs(region_root, status, started_at DESC);

-- ----------------------------------------------------------------
-- 2) Candidate intake table
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.location_candidates (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
  run_id              UUID NOT NULL REFERENCES public.ingestion_runs(id) ON DELETE CASCADE,
  existing_location_id BIGINT REFERENCES public.locations(id) ON DELETE SET NULL,
  region_root         TEXT NOT NULL,
  region_source       TEXT,
  source              TEXT NOT NULL DEFAULT 'osm',
  source_id           TEXT,
  source_fingerprint  TEXT NOT NULL,
  status              TEXT NOT NULL DEFAULT 'new' CHECK (
    status IN ('new', 'enriched', 'scored', 'approved', 'rejected', 'promoted', 'needs_review')
  ),
  name                TEXT NOT NULL,
  amenity             TEXT,
  cuisine             TEXT,
  address             TEXT,
  city                TEXT,
  website             TEXT,
  phone               TEXT,
  lat                 DOUBLE PRECISION,
  lng                 DOUBLE PRECISION,
  osm_id              BIGINT,
  osm_type            TEXT,
  raw_payload         JSONB NOT NULL DEFAULT '{}'::jsonb,
  enriched_signals    JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_error          TEXT,
  CONSTRAINT location_candidates_source_fingerprint_key UNIQUE (source_fingerprint)
);

CREATE INDEX IF NOT EXISTS idx_location_candidates_run_status
  ON public.location_candidates(run_id, status);

CREATE INDEX IF NOT EXISTS idx_location_candidates_region_status
  ON public.location_candidates(region_root, status);

CREATE INDEX IF NOT EXISTS idx_location_candidates_existing_location
  ON public.location_candidates(existing_location_id)
  WHERE existing_location_id IS NOT NULL;

-- ----------------------------------------------------------------
-- 3) Source evidence per candidate
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.location_source_evidence (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id   BIGINT NOT NULL REFERENCES public.location_candidates(id) ON DELETE CASCADE,
  source         TEXT NOT NULL CHECK (source IN ('osm', 'website', 'google', 'tripadvisor')),
  payload_json   JSONB NOT NULL DEFAULT '{}'::jsonb,
  signals_json   JSONB NOT NULL DEFAULT '{}'::jsonb,
  fetched_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
  ok             BOOLEAN NOT NULL DEFAULT true,
  error          TEXT
);

CREATE INDEX IF NOT EXISTS idx_location_source_evidence_candidate
  ON public.location_source_evidence(candidate_id, source, fetched_at DESC);

-- ----------------------------------------------------------------
-- 4) AI reviews per candidate/reaudit
-- ----------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.location_ai_reviews (
  id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  candidate_id         BIGINT REFERENCES public.location_candidates(id) ON DELETE CASCADE,
  existing_location_id BIGINT REFERENCES public.locations(id) ON DELETE SET NULL,
  model                TEXT NOT NULL,
  prompt_version       TEXT NOT NULL DEFAULT 'v1',
  score_10             SMALLINT NOT NULL CHECK (score_10 BETWEEN 0 AND 10),
  confidence           NUMERIC(4,3) NOT NULL CHECK (confidence >= 0 AND confidence <= 1),
  is_suitable          BOOLEAN,
  decision             TEXT NOT NULL CHECK (decision IN ('approved', 'rejected', 'needs_review')),
  reason_short         TEXT,
  reasons_json         JSONB NOT NULL DEFAULT '[]'::jsonb,
  risk_flags           JSONB NOT NULL DEFAULT '[]'::jsonb,
  derived_fields       JSONB NOT NULL DEFAULT '{}'::jsonb,
  raw_json             JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_location_ai_reviews_candidate_created
  ON public.location_ai_reviews(candidate_id, created_at DESC)
  WHERE candidate_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_location_ai_reviews_existing_location
  ON public.location_ai_reviews(existing_location_id, created_at DESC)
  WHERE existing_location_id IS NOT NULL;

-- ----------------------------------------------------------------
-- 5) Extend production locations with AI metadata
-- ----------------------------------------------------------------
ALTER TABLE public.locations
  ADD COLUMN IF NOT EXISTS ai_suitability_score_10 NUMERIC(4,1),
  ADD COLUMN IF NOT EXISTS ai_suitability_confidence NUMERIC(4,3),
  ADD COLUMN IF NOT EXISTS ai_reviewed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS ai_review_model TEXT,
  ADD COLUMN IF NOT EXISTS ai_review_version TEXT,
  ADD COLUMN IF NOT EXISTS ai_review_status TEXT;

CREATE INDEX IF NOT EXISTS idx_locations_ai_review_status
  ON public.locations(ai_review_status)
  WHERE ai_review_status IS NOT NULL;

-- ----------------------------------------------------------------
-- 6) Candidate updated_at trigger
-- ----------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.set_location_candidates_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS location_candidates_updated_at ON public.location_candidates;
CREATE TRIGGER location_candidates_updated_at
  BEFORE UPDATE ON public.location_candidates
  FOR EACH ROW EXECUTE FUNCTION public.set_location_candidates_updated_at();
